export const skipTags = [
    'a',
    // 'abbr',
    // 'audio',
    'b',
    'br',
    // 'canvas',
    'dd',
    'dl',
    'dt',
    'em',
    // 'form',
    // 'h1',
    // 'h2',
    // 'h3',
    // 'h4',
    // 'h5',
    // 'h6',
    'div',
    'embed',
    'noindex',
    'noscript',
    'hr',
    'i',
    'iframe',
    'img',
    // 'input',
    // 'label',
    // 'legend',
    'li',
    'ol',
    'optgroup',
    'option',
    'p',
    'pre',
    'picture',
    'small',
    's',

    // 'select',
    'small',
    'span',
    'strong',
    'sub',
    'sup',
    'table',
    'tbody',
    'td',
    // 'textarea',
    'tfoot',
    'th',
    'thead',
    // 'time',
    'tr',
    'u',
    'ul',
    // 'video',

    // svg
    'svg',
    // 'circle',
    // 'rect',
    // 'path',
    // 'line',
    // 'ellipse',
    // 'defs',
    // 'g',

    'feBlend',
    'feColorMatrix',
    'feComponentTransfer',
    'feComposite',
    'feConvolveMatrix',
    'feDiffuseLighting',
    'feDisplacementMap',
    'feDistantLight',
    'feFlood',
    'feFuncA',
    'feFuncB',
    'feFuncG',
    'feFuncR',
    'feGaussianBlur',
    'feImage',
    'feMerge',
    'feMergeNode',
    'feMorphology',
    'feOffset',
    'fePointLight',
    'feSpecularLighting',
    'feSpotLight',
    'feTile',
    'feTurbulence',


    // 'address',
    // 'area',
    // 'article',
    // 'aside',
    // 'bdi',
    // 'bdo',
    // 'big',
    // 'blockquote',
    // 'button',
    // 'caption',
    // 'cite',
    // 'code',
    // 'col',
    // 'colgroup',
    // 'data',
    // 'datalist',
    // 'del',
    // 'details',
    // 'dfn',
    // 'dialog',
    // 'fieldset',
    // 'figcaption',
    // 'figure',
    // 'footer',
    // 'header',
    // 'hgroup',
    // 'ins',
    // 'kbd',
    // 'keygen',
    // 'main',
    // 'map',
    // 'mark',
    // 'menu',
    // 'menuitem',
    // 'meter',
    // 'nav',
    // 'object',
    // 'output',
    // 'param',
    // 'progress',
    // 'q',
    // 'rp',
    // 'rt',
    // 'ruby',
    // 'samp',
    // 'section',
    // 'source',
    // 'summary',
    // 'time',
    // 'track',
    // 'wbr',
    // 'webview',
    // // svg
    // 'animate',
    // 'animateTransform',
    // 'clipPath',
    // 'desc',
    // 'filter',
    // 'foreignObject',
    // 'image',
    // 'linearGradient',
    // 'marker',
    // 'mask',
    // 'metadata',
    // 'pattern',
    // 'polygon',
    // 'polyline',
    // 'radialGradient',
    // 'stop',
    // 'switch',
    // 'symbol',
    // 'text',
    // 'textPath',
    // 'tspan',
    // 'use',
    // 'view',
];
export const htmlTags = [
    // head tags
    // 'title',
    // 'meta',
    // 'head',
    // 'body',
    // 'html',
    // 'link',
    // 'style',
    // 'script',
    // 'base',

    'a',
    'abbr',
    'address',
    'area',
    'article',
    'aside',
    'audio',
    'b',
    'bdi',
    'bdo',
    'big',
    'blockquote',
    'br',
    'button',
    'canvas',
    'caption',
    'cite',
    'code',
    'col',
    'colgroup',
    'data',
    'datalist',
    'dd',
    'del',
    'details',
    'dfn',
    'dialog',
    'div',
    'dl',
    'dt',
    'em',
    'embed',
    'fieldset',
    'figcaption',
    'figure',
    'footer',
    'form',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'header',
    'hgroup',
    'hr',
    'i',
    'iframe',
    'img',
    'input',
    'ins',
    'kbd',
    'keygen',
    'label',
    'legend',
    'li',
    'main',
    'map',
    'mark',
    'menu',
    'menuitem',
    'meter',
    'nav',
    'noindex',
    'noscript',
    'object',
    'ol',
    'optgroup',
    'option',
    'output',
    'p',
    'param',
    'picture',
    'pre',
    'progress',
    'q',
    'rp',
    'rt',
    'ruby',
    's',
    'samp',
    'section',
    'select',
    'small',
    'source',
    'span',
    'strong',
    'sub',
    'summary',
    'sup',
    'table',
    'tbody',
    'td',
    'textarea',
    'tfoot',
    'th',
    'thead',
    'time',
    'tr',
    'track',
    'u',
    'ul',
    'video',
    'wbr',
    'webview',
    'svg',
    'animate',
    'animateTransform',
    'circle',
    'clipPath',
    'defs',
    'desc',
    'ellipse',
    'feBlend',
    'feColorMatrix',
    'feComponentTransfer',
    'feComposite',
    'feConvolveMatrix',
    'feDiffuseLighting',
    'feDisplacementMap',
    'feDistantLight',
    'feFlood',
    'feFuncA',
    'feFuncB',
    'feFuncG',
    'feFuncR',
    'feGaussianBlur',
    'feImage',
    'feMerge',
    'feMergeNode',
    'feMorphology',
    'feOffset',
    'fePointLight',
    'feSpecularLighting',
    'feSpotLight',
    'feTile',
    'feTurbulence',
    'filter',
    'foreignObject',
    'g',
    'image',
    'line',
    'linearGradient',
    'marker',
    'mask',
    'metadata',
    'path',
    'pattern',
    'polygon',
    'polyline',
    'radialGradient',
    'rect',
    'stop',
    'switch',
    'symbol',
    'text',
    'textPath',
    'tspan',
    'use',
    'view',
];
